### ISSUE TITLE
"Mon" Crashes

### ISSUE THREAD

**Issue by msj121** [msj121/datepy#1]
```
from datepy import datepy
datepy.convert_to_rfc3339("Mon")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/datepy/datepy.py", line 102, in convert_to_rfc3339
    new_date_str = remove_days_of_week(date_str)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datepy/datepy.py", line 48, in remove_days_of_week
    if toreturn[-1] == "," or toreturn[-1] == ".":
       ~~~~~~~~^^^^
IndexError: string index out of range
```

**Comment by msj121** [comment]
Fixed with 0.1.7
